swagger: '2.0'
info:
  version: 1.0.0
  title: Node Swagger Exampol
  license:
    name: Proprietary
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
  '/swagger.json':
    get:
      tags:
        - Spec
      operationId: getSwaggerSpec
      description: |
        Get Swagger Spec
      responses:
        '200':
          description: Successful
          schema:
            type: string
  '/register':
    post:
      tags:
        - Register
      operationId: Register
      parameters:
        - name: user
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
              password:
                type: string    
      description: |
        Register User
      responses:
        '200':
          description: Successful
          schema:
            type: string
    get:
      tags:
        - Register
      operationId: GetRegister   
      description: |
        Get Registered User      
      responses:
        '200':
          description: Successful
          schema:
            type: object
  '/register/{id}':
    get:
      tags:
        - Register
      operationId: GetRegisteredUserById
      parameters:
        - $ref: '#/parameters/id'    
      description: |
        Get Registered User      
      responses:
        '200':
          description: Successful
          schema:
            type: object
    put:
      tags:
        - Register
      operationId: UpdateRegisteredUserById
      parameters:
        - $ref: '#/parameters/id'
        - name: user
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
              password:
                type: string 
      description: |
        Update Registered User      
      responses:
        '200':
          description: Successful
          schema:
            type: object
    delete:
      tags:
        - Register
      operationId: DeleteRegisteredUserById
      parameters:
        - $ref: '#/parameters/id'
      description: |
        DeleteRegisteredUserById      
      responses:
        '200':
          description: Successful
          schema:
            type: object

parameters:
  id:
    in: path
    name: id
    required: true 
    type: string
